### ISSUE TITLE
Introduce convention: tag with the filename

### ISSUE THREAD

**Issue by reka** [sourcery-ai/sourcery-rules#6]
1.)
> Did I understand correctly, that I can put the following in my project's .sourcery.yaml file:

```yaml
rule_settings:
  enable:
    - default 
    - gpsg
```

Yes, exactly. :+1: 
This will add all the rules that belong to the `gpsg` tag to your project's rule set.

2.) What about the rules in the `remove_debugging_statements.yaml` ?

All rules in this file have the tag `no-debug`.
=> 
You can enable them like this:

```yaml
rule_settings:
  enable:
    - default 
    - gpsg
    - no-debug
 ```

Please note: The `no-debug` rules (incl. yours) will be available only after the next release of Sourcery. (Perhaps next week.)

Reading your question, I realize:
We could introduce a new convention. That we always have a tag that is the same as the file name.
So in `remove-debugging-statements.yaml`, all rules have the tag `remove-debugging-statements`
@angrycaptain19 What do you think?

_Originally posted by @reka in https://github.com/sourcery-ai/sourcery-rules/issues/5#issuecomment-1397048598_
