### ISSUE TITLE
how to get quotation marks in a replacement

### ISSUE THREAD

**Issue by lasinludwig** [sourcery-ai/sourcery-rules#8]
Hi there,

I'm trying to write a rule concerning plotly figures. You can access the underlying data and layout of a figure in two ways:

`fig.data` / `fig.layout` 
or
`fig.to_dict["data"]` / `fig.to_dict["layout"]`

I recently found out that the first option is a little problematic with typing etc. so I'm trying to write a rule that reminds me to use the second option. This is my first try, which doesn't quite work as intended:

```
  - id: use-to_dict
    description: Instead of using fig.foo, use fig.to_dict()["foo"] to get to the underlying data of a plotly figure
    pattern: fig.${item}
    condition: |
      item.starts_with("data")
      or item.starts_with("layout")
    replacement: fig.to_dict()["${item}"]
    tests:
      - match: fig.data
      - match: fig.layout
      - no-match: fig.foo
      - no-match: fig.bar
    tags:
      - plotly
``` 

Question: **How do I put the quotation marks in the replacement?**
(When I use it like shown, it replaces `fig.data` with `fig.to_dict()[data]` - leaving out the quotation marks, which I need.)

Bonus Question: How do I make it work if I don't use `fig` as name for the figure?

Thanks for your help!

**Comment by ruancomelli** [comment]
Hello, @lasinludwig!

Thanks for opening this issue, and I'm sorry for the delay.
Unfortunately, it is not yet possible to convert identifiers to literal strings in replacements, but that is an excellent idea that we will consider adding to the engine.

I think that the best option, for now, is to simply remove the `replacement` field and have this rule as one that has to be manually fixed.

Regarding covering other names besides `fig`, you can convert it to a capture and test against all of the names you normally give to figures:
```yaml
  - id: use-to_dict
    description: Instead of using fig.foo, use fig.to_dict()["foo"] to get to the underlying data of a plotly figure
    pattern: ${fig}.${item}
    condition: |
      (
          fig.equals("f")
          or fig.equals("fig")
          or fig.equals("figure")
      )
      and (
          item.starts_with("data")
          or item.starts_with("layout")
      )
    tests:
      - match: fig.data
      - match: fig.layout
      - match: figure.data
      - no-match: fig.foo
      - no-match: fig.bar
    tags:
      - plotly
```

_(Spoiler alert: we are working towards making this kind of rule much easier to write in the future)_

The ideal solution, instead of writing `fig.equals("fig") or fig.equals("figure")` would be to use the [`has_type`](https://docs.sourcery.ai/Reference/Custom-Rules/conditions/#has_type) condition. However, it is still not powerful enough to correctly infer types in third-party libraries, so matching by name is the best solution for now.
